// Generated Code - DO NOT EDIT !!
// generated by 'emugen'

#ifndef GUARD_magma_encoder_context_t
#define GUARD_magma_encoder_context_t

#include "gfxstream/guest/ChecksumCalculator.h"
#include "gfxstream/guest/IOStream.h"
#include "magma_client_context.h"


#include <stdint.h>

struct magma_encoder_context_t : public magma_client_context_t {

	gfxstream::guest::IOStream *m_stream;
	gfxstream::guest::ChecksumCalculator *m_checksumCalculator;

	magma_encoder_context_t(gfxstream::guest::IOStream *stream, gfxstream::guest::ChecksumCalculator *checksumCalculator);
	virtual uint64_t lockAndWriteDma(void*, uint32_t) { return 0; }
};

#endif  // GUARD_magma_encoder_context_t
